// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Look struct {
	ID               int32          `json:"id"`
	UsuarioID        int32          `json:"usuario_id"`
	Nombre           string         `json:"nombre"`
	Descripcion      sql.NullString `json:"descripcion"`
	Ocasion          string         `json:"ocasion"`
	Temporada        string         `json:"temporada"`
	PrendaEstrellaID sql.NullInt32  `json:"prenda_estrella_id"`
	UrlImagen        string         `json:"url_imagen"`
	Estilo           sql.NullString `json:"estilo"`
	FechaCreacion    sql.NullTime   `json:"fecha_creacion"`
}

type MeGustaLook struct {
	UsuarioID     int32        `json:"usuario_id"`
	LookID        int32        `json:"look_id"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}

type Prenda struct {
	ID            int32        `json:"id"`
	UsuarioID     int32        `json:"usuario_id"`
	Nombre        string       `json:"nombre"`
	Categoria     string       `json:"categoria"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}

type Usuario struct {
	ID            int32        `json:"id"`
	Nombre        string       `json:"nombre"`
	Email         string       `json:"email"`
	FechaCreacion sql.NullTime `json:"fecha_creacion"`
}
