// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const actualizarLook = `-- name: ActualizarLook :one
UPDATE looks
SET nombre = $2,
    descripcion = $3,
    ocasion = $4,
    temporada = $5,
    prenda_estrella_id = $6,
    url_imagen = $7,
    estilo = $8
WHERE id = $1
RETURNING id, usuario_id, nombre, descripcion, ocasion, temporada, prenda_estrella_id, url_imagen, estilo, fecha_creacion
`

type ActualizarLookParams struct {
	ID               int32          `json:"id"`
	Nombre           string         `json:"nombre"`
	Descripcion      sql.NullString `json:"descripcion"`
	Ocasion          string         `json:"ocasion"`
	Temporada        string         `json:"temporada"`
	PrendaEstrellaID sql.NullInt32  `json:"prenda_estrella_id"`
	UrlImagen        string         `json:"url_imagen"`
	Estilo           sql.NullString `json:"estilo"`
}

func (q *Queries) ActualizarLook(ctx context.Context, arg ActualizarLookParams) (Look, error) {
	row := q.db.QueryRowContext(ctx, actualizarLook,
		arg.ID,
		arg.Nombre,
		arg.Descripcion,
		arg.Ocasion,
		arg.Temporada,
		arg.PrendaEstrellaID,
		arg.UrlImagen,
		arg.Estilo,
	)
	var i Look
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nombre,
		&i.Descripcion,
		&i.Ocasion,
		&i.Temporada,
		&i.PrendaEstrellaID,
		&i.UrlImagen,
		&i.Estilo,
		&i.FechaCreacion,
	)
	return i, err
}

const contarMeGustaPorLook = `-- name: ContarMeGustaPorLook :one
SELECT COUNT(*) FROM me_gusta_looks WHERE look_id = $1
`

func (q *Queries) ContarMeGustaPorLook(ctx context.Context, lookID int32) (int64, error) {
	row := q.db.QueryRowContext(ctx, contarMeGustaPorLook, lookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const crearLook = `-- name: CrearLook :one

INSERT INTO looks (
    usuario_id, nombre, descripcion, ocasion, temporada, prenda_estrella_id, url_imagen, estilo
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, usuario_id, nombre, descripcion, ocasion, temporada, prenda_estrella_id, url_imagen, estilo, fecha_creacion
`

type CrearLookParams struct {
	UsuarioID        int32          `json:"usuario_id"`
	Nombre           string         `json:"nombre"`
	Descripcion      sql.NullString `json:"descripcion"`
	Ocasion          string         `json:"ocasion"`
	Temporada        string         `json:"temporada"`
	PrendaEstrellaID sql.NullInt32  `json:"prenda_estrella_id"`
	UrlImagen        string         `json:"url_imagen"`
	Estilo           sql.NullString `json:"estilo"`
}

// ===== LOOKS (CRUD principal) =====
func (q *Queries) CrearLook(ctx context.Context, arg CrearLookParams) (Look, error) {
	row := q.db.QueryRowContext(ctx, crearLook,
		arg.UsuarioID,
		arg.Nombre,
		arg.Descripcion,
		arg.Ocasion,
		arg.Temporada,
		arg.PrendaEstrellaID,
		arg.UrlImagen,
		arg.Estilo,
	)
	var i Look
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nombre,
		&i.Descripcion,
		&i.Ocasion,
		&i.Temporada,
		&i.PrendaEstrellaID,
		&i.UrlImagen,
		&i.Estilo,
		&i.FechaCreacion,
	)
	return i, err
}

const crearPrenda = `-- name: CrearPrenda :one

INSERT INTO prendas (usuario_id, nombre, categoria) VALUES ($1, $2, $3) RETURNING id, usuario_id, nombre, categoria, fecha_creacion
`

type CrearPrendaParams struct {
	UsuarioID int32  `json:"usuario_id"`
	Nombre    string `json:"nombre"`
	Categoria string `json:"categoria"`
}

// ===== PRENDAS =====
func (q *Queries) CrearPrenda(ctx context.Context, arg CrearPrendaParams) (Prenda, error) {
	row := q.db.QueryRowContext(ctx, crearPrenda, arg.UsuarioID, arg.Nombre, arg.Categoria)
	var i Prenda
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nombre,
		&i.Categoria,
		&i.FechaCreacion,
	)
	return i, err
}

const crearUsuario = `-- name: CrearUsuario :one

INSERT INTO usuarios (nombre, email) VALUES ($1, $2) RETURNING id, nombre, email, fecha_creacion
`

type CrearUsuarioParams struct {
	Nombre string `json:"nombre"`
	Email  string `json:"email"`
}

// ===== USUARIOS =====
func (q *Queries) CrearUsuario(ctx context.Context, arg CrearUsuarioParams) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, crearUsuario, arg.Nombre, arg.Email)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.FechaCreacion,
	)
	return i, err
}

const darMeGusta = `-- name: DarMeGusta :exec

INSERT INTO me_gusta_looks (usuario_id, look_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type DarMeGustaParams struct {
	UsuarioID int32 `json:"usuario_id"`
	LookID    int32 `json:"look_id"`
}

// ===== ME GUSTA (like tipo Instagram) =====
func (q *Queries) DarMeGusta(ctx context.Context, arg DarMeGustaParams) error {
	_, err := q.db.ExecContext(ctx, darMeGusta, arg.UsuarioID, arg.LookID)
	return err
}

const eliminarLook = `-- name: EliminarLook :exec
DELETE FROM looks WHERE id = $1
`

func (q *Queries) EliminarLook(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarLook, id)
	return err
}

const eliminarPrenda = `-- name: EliminarPrenda :exec
DELETE FROM prendas WHERE id = $1
`

func (q *Queries) EliminarPrenda(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, eliminarPrenda, id)
	return err
}

const limpiarClosetPorUsuario = `-- name: LimpiarClosetPorUsuario :exec
DELETE FROM prendas WHERE usuario_id = $1
`

func (q *Queries) LimpiarClosetPorUsuario(ctx context.Context, usuarioID int32) error {
	_, err := q.db.ExecContext(ctx, limpiarClosetPorUsuario, usuarioID)
	return err
}

const listarLooksConDetalle = `-- name: ListarLooksConDetalle :many
SELECT
    l.id, l.nombre, l.descripcion, l.ocasion, l.temporada, l.url_imagen, l.estilo, l.fecha_creacion,
    u.nombre AS autora,
    p.nombre AS prenda_estrella
FROM looks l
JOIN usuarios u ON l.usuario_id = u.id
LEFT JOIN prendas p ON l.prenda_estrella_id = p.id
ORDER BY l.fecha_creacion DESC
`

type ListarLooksConDetalleRow struct {
	ID             int32          `json:"id"`
	Nombre         string         `json:"nombre"`
	Descripcion    sql.NullString `json:"descripcion"`
	Ocasion        string         `json:"ocasion"`
	Temporada      string         `json:"temporada"`
	UrlImagen      string         `json:"url_imagen"`
	Estilo         sql.NullString `json:"estilo"`
	FechaCreacion  sql.NullTime   `json:"fecha_creacion"`
	Autora         string         `json:"autora"`
	PrendaEstrella sql.NullString `json:"prenda_estrella"`
}

func (q *Queries) ListarLooksConDetalle(ctx context.Context) ([]ListarLooksConDetalleRow, error) {
	rows, err := q.db.QueryContext(ctx, listarLooksConDetalle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLooksConDetalleRow
	for rows.Next() {
		var i ListarLooksConDetalleRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Ocasion,
			&i.Temporada,
			&i.UrlImagen,
			&i.Estilo,
			&i.FechaCreacion,
			&i.Autora,
			&i.PrendaEstrella,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLooksPorOcasion = `-- name: ListarLooksPorOcasion :many
SELECT id, usuario_id, nombre, descripcion, ocasion, temporada, prenda_estrella_id, url_imagen, estilo, fecha_creacion FROM looks WHERE ocasion = $1 ORDER BY fecha_creacion DESC
`

func (q *Queries) ListarLooksPorOcasion(ctx context.Context, ocasion string) ([]Look, error) {
	rows, err := q.db.QueryContext(ctx, listarLooksPorOcasion, ocasion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Look
	for rows.Next() {
		var i Look
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Nombre,
			&i.Descripcion,
			&i.Ocasion,
			&i.Temporada,
			&i.PrendaEstrellaID,
			&i.UrlImagen,
			&i.Estilo,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLooksPorPrenda = `-- name: ListarLooksPorPrenda :many
SELECT l.id, l.usuario_id, l.nombre, l.descripcion, l.ocasion, l.temporada, l.prenda_estrella_id, l.url_imagen, l.estilo, l.fecha_creacion
FROM looks l
JOIN prendas p ON l.prenda_estrella_id = p.id
WHERE p.nombre ILIKE '%' || $1 || '%'
ORDER BY l.fecha_creacion DESC
`

func (q *Queries) ListarLooksPorPrenda(ctx context.Context, dollar_1 sql.NullString) ([]Look, error) {
	rows, err := q.db.QueryContext(ctx, listarLooksPorPrenda, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Look
	for rows.Next() {
		var i Look
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Nombre,
			&i.Descripcion,
			&i.Ocasion,
			&i.Temporada,
			&i.PrendaEstrellaID,
			&i.UrlImagen,
			&i.Estilo,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarLooksPorUsuario = `-- name: ListarLooksPorUsuario :many
SELECT
    l.id, l.nombre, l.descripcion, l.ocasion, l.temporada, l.url_imagen, l.estilo, l.fecha_creacion,
    u.nombre AS autora,
    p.nombre AS prenda_estrella
FROM looks l
JOIN usuarios u ON l.usuario_id = u.id
LEFT JOIN prendas p ON l.prenda_estrella_id = p.id
WHERE l.usuario_id = $1
ORDER BY l.fecha_creacion DESC
`

type ListarLooksPorUsuarioRow struct {
	ID             int32          `json:"id"`
	Nombre         string         `json:"nombre"`
	Descripcion    sql.NullString `json:"descripcion"`
	Ocasion        string         `json:"ocasion"`
	Temporada      string         `json:"temporada"`
	UrlImagen      string         `json:"url_imagen"`
	Estilo         sql.NullString `json:"estilo"`
	FechaCreacion  sql.NullTime   `json:"fecha_creacion"`
	Autora         string         `json:"autora"`
	PrendaEstrella sql.NullString `json:"prenda_estrella"`
}

func (q *Queries) ListarLooksPorUsuario(ctx context.Context, usuarioID int32) ([]ListarLooksPorUsuarioRow, error) {
	rows, err := q.db.QueryContext(ctx, listarLooksPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListarLooksPorUsuarioRow
	for rows.Next() {
		var i ListarLooksPorUsuarioRow
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Descripcion,
			&i.Ocasion,
			&i.Temporada,
			&i.UrlImagen,
			&i.Estilo,
			&i.FechaCreacion,
			&i.Autora,
			&i.PrendaEstrella,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarPrendasPorUsuario = `-- name: ListarPrendasPorUsuario :many
SELECT id, usuario_id, nombre, categoria, fecha_creacion FROM prendas WHERE usuario_id = $1 ORDER BY nombre
`

func (q *Queries) ListarPrendasPorUsuario(ctx context.Context, usuarioID int32) ([]Prenda, error) {
	rows, err := q.db.QueryContext(ctx, listarPrendasPorUsuario, usuarioID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Prenda
	for rows.Next() {
		var i Prenda
		if err := rows.Scan(
			&i.ID,
			&i.UsuarioID,
			&i.Nombre,
			&i.Categoria,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listarUsuarios = `-- name: ListarUsuarios :many
SELECT id, nombre, email, fecha_creacion FROM usuarios ORDER BY nombre
`

func (q *Queries) ListarUsuarios(ctx context.Context) ([]Usuario, error) {
	rows, err := q.db.QueryContext(ctx, listarUsuarios)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Usuario
	for rows.Next() {
		var i Usuario
		if err := rows.Scan(
			&i.ID,
			&i.Nombre,
			&i.Email,
			&i.FechaCreacion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const obtenerLookConDetalle = `-- name: ObtenerLookConDetalle :one
SELECT
    l.id, l.nombre, l.descripcion, l.ocasion, l.temporada, l.url_imagen, l.estilo, l.fecha_creacion,
    u.nombre AS autora,
    p.nombre AS prenda_estrella
FROM looks l
JOIN usuarios u ON l.usuario_id = u.id
LEFT JOIN prendas p ON l.prenda_estrella_id = p.id
WHERE l.id = $1
`

type ObtenerLookConDetalleRow struct {
	ID             int32          `json:"id"`
	Nombre         string         `json:"nombre"`
	Descripcion    sql.NullString `json:"descripcion"`
	Ocasion        string         `json:"ocasion"`
	Temporada      string         `json:"temporada"`
	UrlImagen      string         `json:"url_imagen"`
	Estilo         sql.NullString `json:"estilo"`
	FechaCreacion  sql.NullTime   `json:"fecha_creacion"`
	Autora         string         `json:"autora"`
	PrendaEstrella sql.NullString `json:"prenda_estrella"`
}

func (q *Queries) ObtenerLookConDetalle(ctx context.Context, id int32) (ObtenerLookConDetalleRow, error) {
	row := q.db.QueryRowContext(ctx, obtenerLookConDetalle, id)
	var i ObtenerLookConDetalleRow
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Descripcion,
		&i.Ocasion,
		&i.Temporada,
		&i.UrlImagen,
		&i.Estilo,
		&i.FechaCreacion,
		&i.Autora,
		&i.PrendaEstrella,
	)
	return i, err
}

const obtenerPrenda = `-- name: ObtenerPrenda :one
SELECT id, usuario_id, nombre, categoria, fecha_creacion FROM prendas WHERE id = $1
`

func (q *Queries) ObtenerPrenda(ctx context.Context, id int32) (Prenda, error) {
	row := q.db.QueryRowContext(ctx, obtenerPrenda, id)
	var i Prenda
	err := row.Scan(
		&i.ID,
		&i.UsuarioID,
		&i.Nombre,
		&i.Categoria,
		&i.FechaCreacion,
	)
	return i, err
}

const obtenerUsuario = `-- name: ObtenerUsuario :one
SELECT id, nombre, email, fecha_creacion FROM usuarios WHERE id = $1
`

func (q *Queries) ObtenerUsuario(ctx context.Context, id int32) (Usuario, error) {
	row := q.db.QueryRowContext(ctx, obtenerUsuario, id)
	var i Usuario
	err := row.Scan(
		&i.ID,
		&i.Nombre,
		&i.Email,
		&i.FechaCreacion,
	)
	return i, err
}

const quitarMeGusta = `-- name: QuitarMeGusta :exec
DELETE FROM me_gusta_looks WHERE usuario_id = $1 AND look_id = $2
`

type QuitarMeGustaParams struct {
	UsuarioID int32 `json:"usuario_id"`
	LookID    int32 `json:"look_id"`
}

func (q *Queries) QuitarMeGusta(ctx context.Context, arg QuitarMeGustaParams) error {
	_, err := q.db.ExecContext(ctx, quitarMeGusta, arg.UsuarioID, arg.LookID)
	return err
}

const usuarioLeDioMeGusta = `-- name: UsuarioLeDioMeGusta :one
SELECT EXISTS (
    SELECT 1 FROM me_gusta_looks WHERE usuario_id = $1 AND look_id = $2
)
`

type UsuarioLeDioMeGustaParams struct {
	UsuarioID int32 `json:"usuario_id"`
	LookID    int32 `json:"look_id"`
}

func (q *Queries) UsuarioLeDioMeGusta(ctx context.Context, arg UsuarioLeDioMeGustaParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, usuarioLeDioMeGusta, arg.UsuarioID, arg.LookID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
