services:
  postgresql:
    image: "postgres:16"
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: outfits_db
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: postgres
    volumes: 
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d

volumes: 
  postgres_data:
